---
version: '2'

services:
  zcashd:
    image: electriccoinco/zcashd:latest
    command: "-equihashsolver=tromp -genproclimit=1 -mineraddress=$ECCFAUCET_FUNDINGADDRESS"
    volumes:
      - $ZCASHD_DATADIR:/srv/zcashd/.zcash
      - $ZCASHD_PARMDIR:/srv/zcashd/.zcash-params
    env_file:
      - .env
    mem_limit: 6G
    ports:
      - "127.0.0.1:$ZCASHD_RPCPORT:$ZCASHD_RPCPORT"
  eccfaucet:
    image: electriccoinco/eccfaucet
    env_file:
      - .env
    mem_limit: 512M
    ports:
      - "$ECCFAUCET_LISTENPORT:$ECCFAUCET_LISTENPORT"

